- name: play level var
  hosts: local
  connection: local
  vars_files:
   - course.yml
  tasks:
  - name: print var
    vars:
      COURSE: Ansible 
    ansible.builtin.debug:
     msg: "COURSE is:{{COURSE}}, DURATION IS :{{DURATION}} , Trainer is {{Trainer}}"