- name: demo on data types
  hosts: local
  connection: local

  vars:
    PROGRAM: "DevOps with AWS"   # STRING
    DURATION: 140                # INT
    IS_LIVE: true                # BOOL
    DETAILS:
      MONTHS: 4
      TRAINER: "SIVA"
    TOPICS:
      - LINUX
      - SHELL
      - ANSIBLE

  tasks:
  - name: print vars
    ansible.builtin.debug:
       msg: |
         program: "{{ PROGRAM }}"
         duration: "{{ DURATION }}"
         is_live: "{{ IS_LIVE }}"
         details: "{{ DETAILS }}"
         topics: "{{ TOPICS }}"
       
