- name: demo on data types
  host: local
  connections: local
  vars:
   PROGRAM: "DevOps with AWS" #STRING
   DURATION: "140" #INT
   IS_LIVE: true #bool
   DETILS:
     MONTHS: 4
     TRAINER: SIVA
   TOPICS: 
    - LINUX
    - SHELL
    - ANSIBLE
  tasks:
   - name: print vars
      ansible.builtin.debug:
      msg:
       program: {{ PROGRAM }}
       DURATION {{ DURATION }}
       IS_LIVE {{ IS_LIVE }}
       DETILS {{ DETILS }}
       TOPICS {{ TOPICS }}
       
